config/routes.rb
Ativos::Application.routes.draw do

  scope "(:locale)", locale: /en|pt\-BR|en/ do
    resources :companies, except: :destroy do
      resources :fixtures
      resources :providers
      resources :people
      resources :groups
      resources :components
      resources :types
      resources :maintenances do
        collection do
          get 'group_by_period', action: :group_by_period, as: :maintenances_grouped_by_period
        end
      end
      resources :budgets, only: :index
      resources :components
      resources :purchase_requests
      resources :maintenance_requests

      member do
        get 'permissions', as: :permissions
        
        put 'define_permission/:user_id', action: :define_permission, as: :define_permission 
        post 'add_permission', action: :add_permission, as: :add_permission
        put 'remove_permission/:user_id', action: :remove_permission, as: :remove_permission
        put 'define_admin_permission/:user_id', action: :define_admin_permission, as: :define_admin_permission

        put 'approve_request/:request_id', to: 'requests#approve_request', as: :approve_request 
        put 'reprove_request/:request_id', to: 'requests#reprove_request', as: :reprove_request
        put 'back_to_pending/:request_id', to: 'requests#back_to_pending', as: :back_to_pending
      end
    end

    devise_for :users
    get 'users/:id' => 'users#show', as: :user
  end

  root 'application#index'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :cpfCnpj, scope: :company

  before_validation :normalize_cpfCnpj

  has_many :fixtures
  belongs_to :company

  def to_s
    name
  end

private
  def normalize_cpfCnpj
    self[:cpfCnpj] = nil if self[:cpfCnpj].blank?
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  def index
    @providers = @company.providers.page(params[:page])
    respond_with(@providers)
  end

  def show
    respond_with(@provider)
  end

  def new
    @provider = @company.providers.new
    respond_with(@provider)
  end

  def edit
    respond_with(@provider)
  end

  def create
    @provider = @company.providers.create(provider_params)
    respond_with(@company, @provider)
  end

  def update
    @provider.update(provider_params)
    respond_with(@company, @provider)
  end

  def destroy
    @provider.destroy
    redirect_to action: :index
  end

  private
    def set_provider
      @provider = @company.providers.find(params[:id])
    end

    def provider_params
      params.require(:provider).permit(:name, :cpfCnpj, :phone, :localization, :company_id)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.slim
br
= simple_form_for [@company, @provider] do |f|
  = f.error_notification

  = f.input :name
  = f.input :cpfCnpj
  = f.input :phone
  = f.input :localization

  = f.submit class: 'btn btn-success'

app/views/providers/edit.html.slim
h1 = t_title_edit('provider')

== render 'form'

app/views/providers/index.html.slim
h1 = t 'layout.providers'

table class = "table"
  thead
    tr
      th = t_attribute 'provider.name'
      th = t_attribute 'provider.cpfCnpj'
      th = t_attribute 'provider.phone'
      th = t_attribute 'provider.localization'
      th
      th
      th

  tbody
    - @providers.each do |provider|
      tr
        td = provider.name
        td = provider.cpfCnpj
        td = provider.phone
        td = provider.localization
        td = link_to t('helpers.links.show'), [@company, provider]
        td = link_to t('helpers.links.edit'), edit_company_provider_path(@company, provider)
        td = link_to t('helpers.links.destroy'), [@company, provider], data: {:confirm => t('helpers.links.confirm')}, :method => :delete
= paginate @providers

br

= link_to t_title_new('provider'), new_company_provider_path, class: 'btn btn-primary'

app/views/providers/new.html.slim
h1 = t_title_new('provider')

== render 'form'

app/views/providers/show.html.slim
p#notice = notice

= show_for @provider do |f|
  = f.attributes :name, :cpfCnpj, :phone, :localization

.btn-toolbar
  = link_to t('helpers.links.edit'), edit_company_provider_path(@company, @provider), class: 'btn btn-primary'
  = link_to t('helpers.links.back'), company_providers_path, class: 'btn btn-success btn-sm'