config/routes.rb
Ativos::Application.routes.draw do

  scope "(:locale)", locale: /en|pt\-BR|en/ do
    resources :companies, except: :destroy do
      resources :fixtures
      resources :providers
      resources :people
      resources :groups
      resources :components
      resources :types
      resources :maintenances do
        collection do
          get 'group_by_period', action: :group_by_period, as: :maintenances_grouped_by_period
        end
      end
      resources :budgets, only: :index
      resources :components
      resources :purchase_requests
      resources :maintenance_requests

      member do
        get 'permissions', as: :permissions
        
        put 'define_permission/:user_id', action: :define_permission, as: :define_permission 
        post 'add_permission', action: :add_permission, as: :add_permission
        put 'remove_permission/:user_id', action: :remove_permission, as: :remove_permission
        put 'define_admin_permission/:user_id', action: :define_admin_permission, as: :define_admin_permission

        put 'approve_request/:request_id', to: 'requests#approve_request', as: :approve_request 
        put 'reprove_request/:request_id', to: 'requests#reprove_request', as: :reprove_request
        put 'back_to_pending/:request_id', to: 'requests#back_to_pending', as: :back_to_pending
      end
    end

    devise_for :users
    get 'users/:id' => 'users#show', as: :user
  end

  root 'application#index'

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  belongs_to :company
  belongs_to :person
  belongs_to :provider
  belongs_to :type
  belongs_to :purchase_request, foreign_key: 'request_id'
  has_many :component_fixtures, autosave: true, dependent: :delete_all
  has_many :maintenances

  validates_presence_of :number, :type
  validates_uniqueness_of :number, scope: :type

  accepts_nested_attributes_for :component_fixtures, allow_destroy: true

  scope :by_person_id, -> (person_id) { where(person_id: person_id)}
  scope :by_type_id, -> (type_id) { where(type_id: type_id)}
  scope :by_provider_id, -> (provider_id) { where(provider_id: provider_id)}
  scope :by_number, -> (number) { where(number: number)}
  scope :by_acquisition, -> (acquisition) { where(acquisition: acquisition)}

  def to_s
    complete_description
  end

  def complete_description
    type.nil? ? "#{number}" : "#{number} - #{type.description}"
  end

end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  before_action :set_fixture, only: [:show, :edit, :update, :destroy]

  def index
    if search_params
      elements = @company.fixtures

      search_params.each do |key, value|
        elements = elements.send('by_' + key, value) unless value.empty?
      end

      @fixtures = elements.page(params[:page])
    else
      @fixtures = @company.fixtures.page(params[:page])
    end
    respond_with(@fixtures)
  end

  def show
    respond_with(@fixture)
  end

  def new
    @fixture = @company.fixtures.new

    @fixture.acquisition = params[:acquisition]
    @fixture.provider_id = params[:provider_id]
    @fixture.request_id = params[:purchase_request_id]
    @fixture.purchase_value = params[:value]

    respond_with(@fixture)
  end

  def edit
    respond_with(@fixture)
  end

  def create
    @fixture = @company.fixtures.create(fixture_params)
    respond_with(@company, @fixture)
  end

  def update
    @fixture.update(fixture_params)
    respond_with(@company, @fixture)
  end

  def destroy
    @fixture.destroy
    redirect_to action: :index
  end

  private
    def set_fixture
      @fixture = @company.fixtures.find(params[:id])
    end

    def fixture_params
      params.require(:fixture).permit(:number, :warranty, :provider_id, :acquisition, :type_id, :person_id, :purchase_value, :company_id, :request_id, 
        component_fixtures_attributes: [:id, :_destroy, :description, :component_id, :quantity])
    end

    def search_params
      return nil unless params[:search]
      params.require(:search).permit(:number, :provider_id, :type_id, :person_id, :acquisition)
    end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/views/fixtures/_component_fixture_fields.html.slim
tr class = 'nested-fields'
  td = f.association :component, label: false, collection: @company.components
  td = f.input :quantity, label: false
  td = f.input :description, label: false
  td = link_to_remove_association "Remover", f, :class => 'btn btn-danger btn-sm'

app/views/fixtures/_fixtures.html.slim
h1 = t 'layout.fixtures'

table.table
  thead
    tr
      th = t_attribute 'fixture.number'
      th = t_attribute 'fixture.type'
      th = t_attribute 'fixture.person'
      th = t_attribute 'fixture.acquisition'
      th = t_attribute 'fixture.provider'
      th = t_attribute 'fixture.warranty'
      th = t_attribute 'fixture.purchase_value'
      th
      th
      th

  tbody
    - @fixtures.each do |fixture|
      tr
        td = fixture.number
        td = fixture.type
        td = fixture.person
        td = l(fixture.acquisition) if fixture.acquisition
        td = fixture.provider
        td = fixture.warranty
        td = number_to_currency(fixture.purchase_value) if fixture.purchase_value 

        td = link_to t('helpers.links.show'), [@company, fixture]
        td = link_to t('helpers.links.edit'), edit_company_fixture_path(@company, fixture)
        td = link_to t('helpers.links.destroy'), [@company, fixture], data: {:confirm => t('helpers.links.confirm')}, :method => :delete

br

= link_to t_title_new('fixture'), new_company_fixture_path, class: 'btn btn-primary'

app/views/fixtures/_form.html.slim
br
= simple_form_for([current_company, @fixture]) do |f|
  = f.error_notification

  = f.input :number
  = f.association :type, collection: @company.types
  = f.association :person, collection: @company.people
  = f.input :acquisition, html5: true
  = f.association :provider, collection: @company.providers
  = f.input :warranty
  = f.input :purchase_value
  = f.association :purchase_request, collection: @company.purchase_requests.where(status: 1)

  table.table
    thead
      th = t_attribute('component_fixture.component')
      th = t_attribute('component_fixture.quantity')
      th = t_attribute('component_fixture.description')
      th
    tbody id = "body"
      = f.simple_fields_for :component_fixtures do |component_fixture|
         = render 'component_fixture_fields', :f => component_fixture
  .links
    = link_to_add_association t('helpers.links.add'), f, :component_fixtures, class: 'btn btn-sm btn-success', 'data-association-insertion-node' => '#body', 'data-association-insertion-method' => :append

  br
  = f.submit class: 'btn btn-success'

app/views/fixtures/_search.html.slim
= form_tag company_fixtures_path, method: :get do |f|
  - model_path = 'activerecord.attributes.fixture.'
  - search_params = params[:search] ? params[:search] : {}
   
  .row
    .col-md-1 = label_tag 'search[number]', t(model_path + 'number') 
    .col-md-5 = text_field_tag 'search[number]', search_params[:number], class: 'form-control input-sm'

    .col-md-1 = label_tag 'search[type_id]', t(model_path + 'type')
    .col-md-5 = select_tag 'search[type_id]', options_from_collection_for_select(@company.types, "id", "description", search_params[:type_id]), include_blank: true, class: 'form-control input-sm'

  br
  .row
    .col-md-1 = label_tag 'search[person_id]', t(model_path + 'person')
    .col-md-3 = select_tag 'search[person_id]', options_from_collection_for_select(@company.people, "id", "name", search_params[:person_id]), include_blank: true, class: 'form-control input-sm'

    .col-md-1 = label_tag 'search[acquisition]', t(model_path + 'acquisition')
    .col-md-2 = text_field_tag 'search[acquisition]', search_params[:acquisition], class: 'form-control input-sm', data: {provide: 'datepicker'}
    
    .col-md-1 = label_tag 'search[provider_id]', t(model_path + 'provider')
    .col-md-2 = select_tag 'search[provider_id]', options_from_collection_for_select(@company.providers, "id", "name", search_params[:provider_id]), include_blank: true, class: 'form-control input-sm'

    .col-md-2 = submit_tag t('helpers.links.search'), class: 'btn btn-sm btn-primary'
  br

app/views/fixtures/edit.html.slim
h1 = t_title_edit('fixture')

== render 'form'

app/views/fixtures/index.html.slim
h1 = t 'layout.fixtures'

== render 'search'

table.table
  thead
    tr
      th = t_attribute 'fixture.number'
      th = t_attribute 'fixture.type'
      th = t_attribute 'fixture.person'
      th = t_attribute 'fixture.acquisition'
      th = t_attribute 'fixture.provider'
      th = t_attribute 'fixture.warranty'
      th = t_attribute 'fixture.purchase_value'
      th
      th
      th

  tbody
    - @fixtures.each do |fixture|
      tr
        td = fixture.number
        td = fixture.type
        td = fixture.person
        td = l(fixture.acquisition) if fixture.acquisition
        td = fixture.provider
        td = fixture.warranty
        td = number_to_currency(fixture.purchase_value) if fixture.purchase_value 

        td = link_to t('helpers.links.show'), [@company, fixture]
        td = link_to t('helpers.links.edit'), edit_company_fixture_path(@company, fixture)
        td = link_to t('helpers.links.destroy'), [@company, fixture], data: {:confirm => t('helpers.links.confirm')}, :method => :delete
= paginate @fixtures

br

= link_to t_title_new('fixture'), new_company_fixture_path, class: 'btn btn-primary'

app/views/fixtures/new.html.slim
h1 = t_title_new('fixture')

== render 'form'

app/views/fixtures/show.html.slim
p#notice = notice

= show_for @fixture.decorate do |f|
  = f.attributes :number, :type, :person, :acquisition, :provider, :warranty, :purchase_value_to_currency

table.table
  thead
    th = t_attribute('component_fixture.component')
    th = t_attribute('component_fixture.quantity')
    th = t_attribute('component_fixture.description')
  tbody
    - @fixture.component_fixtures.each do |component|
      tr
        td = component.component
        td = component.quantity
        td = component.description

.btn-toolbar
  = link_to t('helpers.links.edit'), edit_company_fixture_path(@company, @fixture), class: 'btn btn-primary'
  = link_to t('helpers.links.back'), company_fixtures_path, class: 'btn btn-success btn-sm'