config/routes.rb
Ativos::Application.routes.draw do

  scope "(:locale)", locale: /en|pt\-BR|en/ do
    resources :companies, except: :destroy do
      resources :fixtures
      resources :providers
      resources :people
      resources :groups
      resources :components
      resources :types
      resources :maintenances do
        collection do
          get 'group_by_period', action: :group_by_period, as: :maintenances_grouped_by_period
        end
      end
      resources :budgets, only: :index
      resources :components
      resources :purchase_requests
      resources :maintenance_requests

      member do
        get 'permissions', as: :permissions
        
        put 'define_permission/:user_id', action: :define_permission, as: :define_permission 
        post 'add_permission', action: :add_permission, as: :add_permission
        put 'remove_permission/:user_id', action: :remove_permission, as: :remove_permission
        put 'define_admin_permission/:user_id', action: :define_admin_permission, as: :define_admin_permission

        put 'approve_request/:request_id', to: 'requests#approve_request', as: :approve_request 
        put 'reprove_request/:request_id', to: 'requests#reprove_request', as: :reprove_request
        put 'back_to_pending/:request_id', to: 'requests#back_to_pending', as: :back_to_pending
      end
    end

    devise_for :users
    get 'users/:id' => 'users#show', as: :user
  end

  root 'application#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
  enum status: [ :pending, :approved, :rejected ]
  
  belongs_to :responsible, class_name: 'User'
  belongs_to :approval_responsible, class_name: 'User'
  belongs_to :company
  belongs_to :budget_approved, class_name: 'Budget'
  has_many :budgets, dependent: :delete_all
  
  accepts_nested_attributes_for :budgets, allow_destroy: true

  validates_presence_of :title, :responsible, :status, :approval_responsible, :date
  validate :validate_budget_approved

  after_initialize :default_values

  scope :by_title, -> (title) { where('title LIKE ?', "%#{title}%")}
  scope :by_description, -> (description) { where('description LIKE ?', "%#{description}%")}
  scope :by_responsible_id, -> (responsible_id) { where(responsible_id: responsible_id)}
  scope :by_status, -> (status) { where(status: status)}
  scope :by_fuxture_id, -> (fixture_id) { where(fixture_id: fixture_id)}
  scope :by_date, -> (date) { where(date: date)}

  def status_i18n
    I18n.translate('enumerize.request.status.' + status)
  end

  def validate_budget_approved
    if approved? 
      if budget_approved.nil?
        errors.add(I18n.translate('request.approved_budget_cant_be_null'))
      end
    else
      if budget_approved
        errors.add(I18n.translate('request.approved_budget_should_be_null'))
      end
    end
  end

private
  def default_values
    self.status ||= 0
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  include RequestsHelper

  before_action :set_request, only: [:approve_request, :reprove_request, :back_to_pending]

  def approve_request
    if (able_to_approve_reprove? @request)
      @request.budget_approved = @request.budgets.where(id: params[:budget_ids]).first
      @request.approved!
    end
    respond_with(@company, location: company_fixtures_path(@company))
  end

  def reprove_request
    @request.rejected! if (able_to_approve_reprove? @request)
    respond_with(@company, location: company_fixtures_path(@company))
  end

  def back_to_pending
    if @request.approval_responsible.eql?(current_user)
      @request.budget_approved = nil
      @request.pending!
    end
    respond_with(@company, location: company_fixtures_path(@company))
  end

protected
  def set_request
    @request = @company.requests.find(params[:request_id])
  end

  def permit(obj)
    attrs = [:title, :date, :description, :fixture_id, budgets_attributes: [:id, :_destroy, :value, :provider_id, :date, :observation]]
    attrs << :approval_responsible_id unless params[:action] == :create

    obj.permit(attrs)
  end

  def search_params
    return nil unless params[:search]
    params.require(:search).permit(:title, :date, :responsible_id, :description, :status, :fixture_id)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper

  def maintenance_request?(request)
    request.type.eql? 'MaintenanceRequest'
  end

  def path(request)
    return maintenance_request?(request) ? company_maintenance_requests_path : company_purchase_requests_path
  end

  def edit_path(company, request)
    return maintenance_request?(request) ? edit_company_maintenance_request_path(@company, request) : 
          edit_company_purchase_request_path(@company, request)
  end

  def able_to_approve_reprove?(request)
    @request.approval_responsible.eql?(current_user) && @request.pending?
  end

end

app/views/requests/_form.html.slim
br
= simple_form_for([@company, request]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :date, html5: true
    = f.input :description
    - if maintenance_request? request
      = f.association :fixture, collection: @company.fixtures
    = f.association :responsible, disabled: true, collection: @company.all_with_permission
    = f.association :approval_responsible, disabled: !request.new_record?, collection: @company.admins

    = render '/budgets/nested_budget_fields', f: f
    
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/requests/_index.html.slim
br
== render 'search', maintenance_request: maintenance_request

table.table
  thead
    tr
      th = t_attribute 'request.title'
      th = t_attribute 'request.date'
      th = t_attribute 'request.responsible'
      - if maintenance_request
        th = t_attribute 'request.fixture'
      th = t_attribute 'request.status'
      th = t_attribute 'request.approval_responsible_short'
      th
      th
      th

  tbody
    - requests.each do |request|
      - klass = request.pending? ? 'warning' : (request.approved? ? 'success' : 'danger')
      tr class = [klass]
        td = truncate_with_hover(request.title)
        td = l(request.date) if request.date
        td = request.responsible
        
        - if maintenance_request
          td = request.fixture
        
        td = request.status_i18n
        td = request.approval_responsible

        td = link_to t('helpers.links.show'), [@company, request]
        td = link_to t('helpers.links.edit'), edit_path(@company, request)
        td = link_to t('helpers.links.destroy'), [@company, request], data: {:confirm => 'Are you sure?'}, :method => :delete
= paginate requests
br

app/views/requests/_search.html.slim
= form_tag({}, {method: :get}) do
  - model_path = 'activerecord.attributes.request.'
  - search_params = params[:search] ? params[:search] : {}

  .row
    .col-md-1 = label_tag 'search[title]', t(model_path + 'title') 
    .col-md-3 = text_field_tag 'search[title]', search_params[:title], class: 'form-control input-sm'

    .col-md-1 = label_tag 'search[responsible_id]', t(model_path + 'responsible')
    .col-md-3 = select_tag 'search[responsible_id]', options_from_collection_for_select(@company.all_users, "id", "full_name", search_params[:responsible_id]), include_blank: true, class: 'form-control input-sm'

    .col-md-1 = label_tag 'search[status]', t(model_path + 'status')
    .col-md-3 = select_tag 'search[status]', options_from_collection_for_select(Request.statuses, "second", "first", search_params[:status]), include_blank: true, class: 'form-control input-sm'

  br
  .row
    - if maintenance_request
      .col-md-1 = label_tag 'search[fixture_id]', t(model_path + 'fixture')
      .col-md-2 = select_tag 'search[fixture_id]', options_from_collection_for_select(@company.fixtures, "id", "complete_description", search_params[:fixture_id]), include_blank: true, class: 'form-control input-sm'

    .col-md-1 = label_tag 'search[description]', t(model_path + 'description')
    .col-md-2 = text_field_tag 'search[description]', search_params[:description], class: 'form-control input-sm'

    .col-md-1 = label_tag 'search[date]', t(model_path + 'date')
    .col-md-2 = text_field_tag 'search[date]', search_params[:date], class: 'form-control input-sm', data: {provide: 'datepicker'}
    
    .col-md-3 = submit_tag t('helpers.links.search'), class: 'btn btn-sm btn-primary'
  br

app/views/requests/_select_orcamento.html.slim
#approve-request-modal.modal.fade
  .modal-dialog
    .modal-content
      = form_tag approve_request_company_path(@company, request), method: :put do
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
          h4 = t('request.select_the budget_approved')
        .modal-body
          dl
            - request.budgets.each do |budget|
              br
              = radio_button_tag "budget_ids[]", budget.id
              = budget.to_s
        .modal-footer
          = submit_tag t('layout.approve_the_budget'), class: 'btn btn-sm btn-success'

app/views/requests/_show.html.slim
p#notice = notice

= show_for request do |f|
  = f.attributes :title, :date, :description, :status_i18n, :approval_responsible
  - if maintenance_request? request
    = f.attribute :fixture
  - if request.approved?
    = f.attribute :budget_approved

h5 = t('layout.budgets')

table.table
  thead
    th = t_attribute('budget.date')
    th = t_attribute('budget.value')
    th = t_attribute('budget.provider')
    th = t_attribute('budget.observation')
  tbody
    - request.budgets.each do |budget|
      tr
        td = l(budget.date)
        td = number_to_currency(budget.value) if budget.value 
        td = budget.provider.name
        td = budget.observation

.btn-toolbar
  - if(request.pending? && current_user.eql?(request.approval_responsible))

    a.btn.btn-success href = '#approve-request-modal' data-toggle = 'modal' 
      = t('layout.approve_request')

    = link_to t('layout.reject_request'), reprove_request_company_path(@company, request), class: 'btn btn-danger', method: :put
  - else
    = link_to t('layout.back_to_pending'), back_to_pending_company_path(@company, request), class: 'btn btn-danger', method: :put

  - if (request.instance_of?(PurchaseRequest) && request.approved?)
    = link_to t('request.create_fixture'), new_company_fixture_path(acquisition: request.date, purchase_request_id: request.id, provider_id: request.budget_approved.provider_id, value: request.budget_approved.value), class: 'btn btn-info'
  = link_to t('helpers.links.edit'), edit_path(@company, request), class: 'btn btn-info'
  = link_to t('helpers.links.back'), path(request), class: 'btn btn-info btn-sm'

  = render 'select_orcamento', request: request