config/routes.rb
Ativos::Application.routes.draw do

  scope "(:locale)", locale: /en|pt\-BR|en/ do
    resources :companies, except: :destroy do
      resources :fixtures
      resources :providers
      resources :people
      resources :groups
      resources :components
      resources :types
      resources :maintenances do
        collection do
          get 'group_by_period', action: :group_by_period, as: :maintenances_grouped_by_period
        end
      end
      resources :budgets, only: :index
      resources :components
      resources :purchase_requests
      resources :maintenance_requests

      member do
        get 'permissions', as: :permissions
        
        put 'define_permission/:user_id', action: :define_permission, as: :define_permission 
        post 'add_permission', action: :add_permission, as: :add_permission
        put 'remove_permission/:user_id', action: :remove_permission, as: :remove_permission
        put 'define_admin_permission/:user_id', action: :define_admin_permission, as: :define_admin_permission

        put 'approve_request/:request_id', to: 'requests#approve_request', as: :approve_request 
        put 'reprove_request/:request_id', to: 'requests#reprove_request', as: :reprove_request
        put 'back_to_pending/:request_id', to: 'requests#back_to_pending', as: :back_to_pending
      end
    end

    devise_for :users
    get 'users/:id' => 'users#show', as: :user
  end

  root 'application#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'

  validates_presence_of :name, :owner

  has_many :fixtures
  has_many :groups
  has_many :components
  has_many :providers
  has_many :types
  has_many :budgets
  has_many :purchase_requests
  has_many :maintenance_requests
  has_many :requests
  
  has_many :maintenances, through: :fixtures
  has_many :people, through: :groups

  has_many :company_users
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_user_for_permission, only: [:define_permission, :define_admin_permission, :remove_permission]

  def index
    if (current_user)
      @companies = Kaminari.paginate_array(current_user.decorate.companies).page(params[:page])
      respond_with(@companies)
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.owner = current_user
    if @company.save
      redirect_to action: :index
    else
      respond_with(@company)
    end
  end

  def update
    @company.update(company_params)
    redirect_to action: :index
  end

  def permissions
  end

  def define_permission
    if current_company.admin? current_user
      company_user = current_company.company_user_by_user(@user_form_permission)
      company_user ||= current_company.company_users.build(user: @user_form_permission)

      company_user.admin = false
      company_user.save
    end

    redirect_to action: 'permissions'
  end

  def add_permission
    if current_company.admin? current_user
      email = add_permission_params[:email]

      user = User.find_by(email: email)

      unless user
        return redirect_to action: 'permissions', notice: "Nenhum Usuário encontrado com o email #{email}" 
      end

      unless current_company.admin? user
        company_user = current_company.company_users.build(user: user)
        company_user.admin = false
        company_user.save
      end
    end

    redirect_to action: 'permissions'
  end

  def remove_permission
    if current_company.admin? current_user
      company_user = current_company.company_user_by_user(@user_form_permission)
      company_user.destroy if company_user
    end

    redirect_to action: 'permissions'
  end

  def define_admin_permission
    if current_company.owner?(current_user)
      company_user = current_company.company_user_by_user(@user_form_permission)
      company_user ||= current_company.company_users.build(admin: true, user: @user_form_permission)
      company_user.admin = true
      company_user.save
    end

    redirect_to action: 'permissions'
  end

private
  def set_company
    @company = current_user.companies.find(params[:id])
  end

  def set_user_for_permission
    @user_form_permission = User.find(params[:user_id])
  end

  def company_params
    params.require(:company).permit(:name, :owner_id)
  end

  def add_permission_params
    params.require(:add_permission).permit(:email)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_add_permission.html.slim
= simple_form_for :add_permission, url: add_permission_company_path do |f|
  = f.input :email
  = f.submit t('helpers.links.add'), class: 'btn btn-success'

app/views/companies/_form.html.slim
br
= simple_form_for(@company) do |f|
  = f.error_notification

  = f.input :name
  = f.button :submit, class: 'btn btn-success'

app/views/companies/_users.html.slim
table.table.table-striped
  tbody
    - current_company.users(context).each do |user|
      - unless current_user.eql?(user)
        tr
          td = link_to(image_tag(avatar_url(user, size: 48), class: 'img-circle'), user_path(user))
          td = user.full_name 
          td = user.email 

          - if context == :admin
            - if current_company.owner?(current_user)
              td = awesome_link 'chevron-down', t('.remove_admin_permission'), define_permission_company_path(current_company, user), method: :put

          - elsif context == :not_admin
            - if current_company.owner?(current_user)
              td = awesome_link 'chevron-up', t('.define_as_admin'), define_admin_permission_company_path(current_company, user), method: :put

            - if current_company.admin?(current_user)
              td = awesome_link 'chevron-down', t('.remove_permission'), remove_permission_company_path(current_company, user), method: :put

          - else
            - if current_company.admin?(current_user)
              td = awesome_link 'chevron-up', t('.add_permission'), define_permission_company_path(current_company, user.id), method: :put

app/views/companies/edit.html.slim
h1 = t_title_edit('company')

= render 'form'

app/views/companies/index.html.slim
- if current_user
  h1
    = t('layout.companies')

  table class="table"
    thead
      tr
        th = t_attribute('company.name')
        th
        th
        /th

    tbody
      - @companies.each do |company|
        tr
          td = company.name
          td = link_to t('.signin'), company_fixtures_path(company)
          - if company.decorate.owner? current_user
            td = link_to t('helpers.links.edit'), edit_company_path(company)
            /td = link_to t('helpers.links.destroy'), company, data: {:confirm => 'Você tem certeza ?'}, :method => :delete
  = paginate @companies

app/views/companies/new.html.slim
h1 = t_title_new('company')

= render 'form'

app/views/companies/permissions.html.slim
h3 = t('.admins')
= render 'users', context: :admin

h3 = t('.users_with_permission')
= render 'users', context: :not_admin

h3 = t('.add_permission')
= render 'add_permission'